### ISSUE TITLE
Exporting entities issue

### ISSUE THREAD

**Issue by rat4m3n** [EE/DataExporter#11]
Hi there,

Nicely done bundle!

I must be doing something wrong...

My implementation is as follows:

```
    $exporter = $this->get('ee.dataexporter');

    $em = $this->getDoctrine()->getManager();
    $entities = $em->getRepository('DigitalUserBundle:User')->findAll();

    $exporter->setOptions('csv', array('fileName' => 'file'));
    $exporter->setColumns(array('[username]' => 'Username', '[firstname]' => 'First name', '[lastname]' => 'Last name', '[email]' => 'Email'));
    $exporter->setData(array($entities));

    return $exporter->render();
```

I get the file generated or html or any other format with no issues ... However my records are empty and only headings are being displayed... What am I doing wrong?

Any tip would be much appreciated.

**Comment by konradpodgorski** [comment]
Hi @rat4m3n 

you shouldn't wrap your property names with braces 

instead

``` php
$exporter->setColumns(array('[username]' => 'Username', '[firstname]' => 'First name', '[lastname]' => 'Last name', '[email]' => 'Email'));
```

write

``` php
$exporter->setColumns(array('username' => 'Username', 'firstname' => 'First name', 'lastname' => 'Last name', 'email' => 'Email'));
```

second issue with you code is fact that you pass

``` php
$exporter->setData(array($entities));
```

when you can just pass ArrayCollection object

``` php
$exporter->setData($entities);
```

**Comment by rat4m3n** [comment]
ha this makes sense! thank a lot Konrad. I ended up doing some preprocessing on array but your way is cleaner and works! thanks a lot.
