### ISSUE TITLE
Can't install your bundle with composer

### ISSUE THREAD

**Issue by XuruDragon** [EE/DataExporter#12]
Composer download the bundle and copy it to my hard drive, I add the class to my AppKerne.php but when I lunch the web sites I have this error :

Fatal error: Class 'EE\DataExporterBundle\EEDataExporterBundle' not found in /var/www/saris/app/AppKernel.php on line 26.

I have followed your instruction like it was wrote.

**Comment by konradpodgorski** [comment]
@XuruDragon are you 100% sure that vendor/ee/dataexporter-bundle/EE/DataExporterBundle exists?

My guess is that you are adding this bundle to existing project you need to run composer with update argument.

``` php
php composer.phar update
```

or if you don't want to update all dependencies you might run just

``` php
php composer.phar update ee/dataexporter-bundle
```

Let me know if that solves your problem

**Comment by XuruDragon** [comment]
Hi 
Yes, I've do that you say, And continue to doesn't work.
It's not the first bundle that µI add to my projects with composer.

I've found a solution by adding directly your bundle in my src folder, it works now....

But I continue to search a solution to add it with composer...

**Comment by piotrantosik** [comment]
@XuruDragon you have this line in autoload_namespace.php (vendor/composer)?

``` php
'EE\\DataExporterBundle' => $vendorDir . '/ee/dataexporter-bundle/',
```

If not run this command in cli and check if the error still occurs:

```
php composer.phar dump-autoload
```

**Comment by konradpodgorski** [comment]
@XuruDragon still it's worth to figure it out, maybe there's a issue somewhere.

check vendor/composer/autoload_namespaces.php if it has 

``` php
'EE\\DataExporterBundle' => $vendorDir . '/ee/dataexporter-bundle/',
```

Fact that it works from scr which is autoloaded by default suggest that there's maybe some conflict in composer, maybe you updated recently?

@Antek88  you were faster :)

**Comment by XuruDragon** [comment]
Yes the line  'EE\DataExporterBundle' => $vendorDir . '/ee/dataexporter-bundle/', is in the vendor/composer/autoload_namespace.php.

Yes I've upgrade composer recently because composer would not update my dependencies if i not upgrade it.

**Comment by piotrantosik** [comment]
@XuruDragon, you write that this error occurs in the browser.
You get the error when you run the command console?, Eg.
`php app / console`
and check if the error persists.
This is most likely a bug in your environment (or composer), you use unix or windows?

**Comment by XuruDragon** [comment]
@Antek88  No, I haven't got any error with the commande console.

**Comment by piotrantosik** [comment]
@XuruDragon can you add this to you AppKernel.php before return occurrence:

```
print_r(get_declared_classes());
```

and check for class EE\DataExporterBundle\EEDataExporterBundle is loaded?

**Comment by XuruDragon** [comment]
I don't think that the class is loaded however it will not crash me with an not found class ^^

I can test, but tomorow.

**Comment by XuruDragon** [comment]
@Antek88 

When I reinstall the bundle with composer and test with 
<code>print_r(get_declared_classes());</code>
there is no EE\DataExporterBundle\EEDataExporterBundle class loaded...

It's not a real problem I made my update with composer and after it, I copy the bundle sources in my src folder where is work done...

thanks @Antek88 and @Konrad-Podgorski for your help even if it doesn't resolve my problem.
