### ISSUE TITLE
PropertyAccess' 

### ISSUE THREAD

**Issue by brunnosantanna** [EE/DataExporter#24]
I am not sure if I missing something, or it is a bug

Symfony\Component\PropertyAccess\PropertyAccess' not found in EE\DataExporterBundle\Service\DataExporter.php on line 192

**Comment by konradpodgorski** [comment]
hi @brunnosantanna 

Property Access Component was introduced in Symfony 2.2, if it's possible upgrade your project. 

Solution for 2.0.x and 2.1.x will be available soon

**Comment by piotrantosik** [comment]
@brunnosantanna please update bundle to latest version and check again. but probably this is not a bug inside bunldle

**Comment by brunnosantanna** [comment]
I installed the PropertyAccess Component. It works fine. thanks!
